obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]
footprint_inflation: 0.1
robot_radius: 0.155
inflation_radius: 0.15
max_obstacle_height: 0.5
min_obstacle_height: 0.05
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
